version: '3.0'

services:





  nginx:

       image: nginx:alpine
       container_name: nginx
       restart: unless-stopped
       tty: true
       ports:
               - "80:80"
               - "443:443"
       volumes:
                 - ./:/var/www/html/
                 - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
       networks:
            - app-network

       depends_on:
         - mysql
         - php

  mysql:

       image: mysql:5.7.32
       container_name: mysql
       restart: unless-stopped
       tty: true
       ports:
                - "3306:3306"


       environment:

           MYSQL_DATABASE: laravel_web
           MYSQL_USER: laravel_web
           MYSQL_PASSWORD: replace_mysql_root_password
           MYSQL_ROOT_PASSWORD: replace_mysql_root_password
           SERVICE_TAGS: dev
           SERVICE_NAME: mysql

       networks:
           - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network








#Docker Networks
networks:
    app-network:
      driver: bridge


